### ISSUE TITLE
Clarification for cmake installation of yaml-cpp

### ISSUE THREAD

**Issue by slamont1** [Collab4exaNBody/doc_exaDEM#10]
The instructions for installing yaml-cpp in the 'Installation With CMake' section (2.1) are only included with the Spack package manager, which seems odd considering this section is for users who will be using CMake.

I suggest adding the location of the source code for yaml-cpp and the corresponding commands for installing yaml-cpp using CMake for users who do not want to install the Spack package manager in the following documentation: docs/source/project_exaDEM/Installation.rst

**Comment by rprat-pro** [comment]
@slamont1 Thank you for pointing out this annoying issue for a new user. I've added a few command lines to install `yaml-cpp` directly as well as the command to add it with `apt get`. Feel free to reopen this issue if it's not satisfactory.
